*Create Wave for each dataset;
data Wave1;
set ADHDNetworkFull (drop=SCID);
Drop SCID;
wave=1;
run;
data Wave2;
set ADHDNetworkFull2;
drop SCID;
wave=2;
run;
data CombinedWaves;
merge Wave1 Wave2;
by AID wave;
run;
*FriendPS over time;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model prob_ADHD= FriendPS wave/solution;
run;
*DifficultyAttention;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model DifficultyAttention= EMDifficultyAttention wave/solution;
run;
*EasilyBored;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model EasilyBored= EMEasilyBored wave/solution;
run;
*GutFeeling;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model GutFeeling= EMGutFeeling wave/solution;
run;
*TroubleRelaxing;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model TroubleRelaxing= EMTroubleRelaxing wave/solution;
run;
*EasilyDistracted;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model EasilyDistracted= EMEasilyDistracted wave/solution;
run;
*TroubleRemembering;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model TroubleRemembering= EMTroubleRemembering wave/solution;
run;
*AvoidHomework;
Proc GLM data=CombinedWaves;
absorb aid;
Class wave;
model AvoidHomework= EMAvoidHomework wave/solution;
run;
